version: "3.8"

services:
    php:
      build:
        context: .
      container_name: php
      volumes:
        - ./src:/var/www/html
      working_dir: /var/www/html
      depends_on:
        - mysql
      environment:
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_PORT: 3306
        DB_DATABASE: dov
        DB_USERNAME: dov-user
        DB_PASSWORD: dovpass
      command: >
        sh -c "composer install &&
               php artisan key:generate &&
               php artisan migrate &&
               chown -R www.data:www-data storage bootstrap/cache &&
               chmod -R 775 storage bootstrap/cache &&
               php-fpm"

    mysql:
      image: mysql:8
      container_name: mysql
      restart: unless-stopped
      environment:
        MYSQL_DATABASE: dov
        MYSQL_USER: dov-user
        MYSQL_PASSWORD: dovpass
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - dbdata:/var/lib/mysql
      ports:
        - "3306:3306"

    nginx:
      image: nginx:alpine
      container_name: nginx
      ports:
        - "8080:80"
      volumes:
        - ./src:/var/www/html
        - ./nginx/default.conf:/etc/nginx/conf.d/defaut.conf
    
volumes:
  dbdata:
        
